// <auto-generated />
using System;
using Denkiishi_v2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Denkiishi_v2.Migrations
{
    [DbContext(typeof(InasDbContext))]
    [Migration("20260107030208_AdicionandoIdentity")]
    partial class AdicionandoIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("kaji_similaridade_id_seq");

            modelBuilder.HasSequence("language_id_seq");

            modelBuilder.HasSequence("lesson_id_seq");

            modelBuilder.HasSequence("level_id_seq");

            modelBuilder.HasSequence("nivel_iten_id_seq");

            modelBuilder.HasSequence("nivel_iten_objetoid_seq");

            modelBuilder.HasSequence("radical_reading_id_seq");

            modelBuilder.HasSequence("usuario_anotacao_id_seq");

            modelBuilder.HasSequence("usuario_sinonimo_kanji_radical_id_seq");

            modelBuilder.Entity("Denkiishi_v2.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Denkiishi_v2.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('cartoes_id_cartao_seq'::regclass)");

                    b.Property<string>("Back")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("back");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DeckId")
                        .HasColumnType("integer")
                        .HasColumnName("deck_id");

                    b.Property<string>("Front")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("front");

                    b.HasKey("Id")
                        .HasName("cartoes_pkey");

                    b.HasIndex("DeckId");

                    b.ToTable("card", (string)null);
                });

            modelBuilder.Entity("Denkiishi_v2.Models.Deck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('baralhos_id_baralho_seq'::regclass)");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("baralhos_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("deck", (string)null);
                });

            modelBuilder.Entity("Denkiishi_v2.Models.Kanji", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("FrequencyRank")
                        .HasColumnType("integer")
                        .HasColumnName("frequency_rank");

                    b.Property<short?>("GradeLevel")
                        .HasColumnType("smallint")
                        .HasColumnName("grade_level");

                    b.Property<bool?>("IsRadical")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_radical");

                    b.Property<short?>("JlptLevel")
                        .HasColumnType("smallint")
                        .HasColumnName("jlpt_level");

                    b.Property<string>("Literal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("literal");

                    b.Property<short?>("StrokeCount")
                        .HasColumnType("smallint")
                        .HasColumnName("stroke_count");

                    b.Property<string>("UnicodeCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unicode_code");

                    b.Property<int?>("WanikaniId")
                        .HasColumnType("integer")
                        .HasColumnName("wanikani_id");

                    b.HasKey("Id")
                        .HasName("kanji_pkey");

                    b.HasIndex(new[] { "WanikaniId" }, "idx_kanji_wanikani_id");

                    b.HasIndex(new[] { "UnicodeCode" }, "kanji_unicode_code_key")
                        .IsUnique();

                    b.ToTable("kanji", (string)null);
                });

            modelBuilder.Entity("Denkiishi_v2.Models.KanjiDecomposition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ComponentKanjiId")
                        .HasColumnType("integer")
                        .HasColumnName("component_kanji_id");

                    b.Property<int?>("ComponentRadicalId")
                        .HasColumnType("integer")
                        .HasColumnName("component_radical_id");

                    b.Property<string>("ComponentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("component_type");

                    b.Property<short?>("DepthLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("depth_level");

                    b.Property<short?>("OrderIndex")
                        .HasColumnType("smallint")
                        .HasColumnName("order_index");

                    b.Property<int>("ParentKanjiId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_kanji_id");

                    b.Property<string>("RelationType")
                        .HasColumnType("text")
                        .HasColumnName("relation_type");

                    b.HasKey("Id")
                        .HasName("kanji_decomposition_pkey");

                    b.HasIndex("ComponentKanjiId");

                    b.HasIndex("ComponentRadicalId");

                    b.HasIndex("ParentKanjiId");

                    b.ToTable("kanji_decomposition", (string)null);
                });

            modelBuilder.Entity("Denkiishi_v2.Models.KanjiMeaning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Gloss")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gloss");

                    b.Property<int?>("IdLanguage")
                        .HasColumnType("integer")
                        .HasColumnName("id_language");

                    b.Property<bool?>("IsPrincipal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_principal");

                    b.Property<int>("KanjiId")
                        .HasColumnType("integer")
                        .HasColumnName("kanji_id");

                    b.HasKey("Id")
                        .HasName("kanji_meaning_pkey");

                    b.HasIndex("IdLanguage");

                    b.HasIndex("KanjiId");

                    b.ToTable("kanji_meaning", (string)null);
                });

            modelBuilder.Entity("Denkiishi_v2.Models.KanjiRadical", b =>
                {
                    b.Property<int>("KanjiId")
                        .HasColumnType("integer")
                        .HasColumnName("kanji_id");

                    b.Property<int>("RadicalId")
                        .HasColumnType("integer")
                        .HasColumnName("radical_id");

                    b.Property<short?>("ImportanceOrd")
                        .HasColumnType("smallint")
                        .HasColumnName("importance_ord");

                    b.Property<string>("Position")
                        .HasColumnType("text")
                        .HasColumnName("position");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("KanjiId", "RadicalId")
                        .HasName("kanji_radical_pkey");

                    b.HasIndex("RadicalId");

                    b.ToTable("kanji_radical", (string)null);
                });

            modelBuilder.Entity("Denkiishi_v2.Models.KanjiReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("KanjiId")
                        .HasColumnType("integer")
                        .HasColumnName("kanji_id");

                    b.Property<string>("ReadingKana")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reading_kana");

                    b.Property<string>("ReadingRomaji")
                        .HasColumnType("text")
                        .HasColumnName("reading_romaji");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("kanji_reading_pkey");

                    b.HasIndex("KanjiId");

                    b.ToTable("kanji_reading", (string)null);
                });

            modelBuilder.Entity("Denkiishi_v2.Models.KanjiSimilarity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('kaji_similaridade_id_seq'::regclass)");

                    b.Property<int?>("IdKanji")
                        .HasColumnType("integer")
                        .HasColumnName("id_kanji");

                    b.Property<int?>("IdKanjiSimilar")
                        .HasColumnType("integer")
                        .HasColumnName("id_kanji_similar");

                    b.HasKey("Id")
                        .HasName("kanji_similaridade_pk");

                    b.HasIndex("IdKanji");

                    b.HasIndex("IdKanjiSimilar");

                    b.ToTable("kanji_similarity", (string)null);
                });

            modelBuilder.Entity("Denkiishi_v2.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("text")
                        .HasColumnName("language_code");

                    b.HasKey("Id")
                        .HasName("language_id_pk");

                    b.ToTable("language", (string)null);
                });

            modelBuilder.Entity("Denkiishi_v2.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("IdKanji")
                        .HasColumnType("integer")
                        .HasColumnName("id_kanji");

                    b.Property<int?>("IdRadical")
                        .HasColumnType("integer")
                        .HasColumnName("id_radical");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text")
                        .HasColumnName("image_path");

                    b.Property<int?>("VocabularyId")
                        .HasColumnType("integer")
                        .HasColumnName("vocabulary_id");

                    b.HasKey("Id")
                        .HasName("lesson_id_pk");

                    b.HasIndex("IdKanji");

                    b.HasIndex("IdRadical");

                    b.HasIndex("VocabularyId");

                    b.ToTable("lesson", (string)null);
                });

            modelBuilder.Entity("Denkiishi_v2.Models.Level", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("level_id_pk");

                    b.ToTable("level", (string)null);
                });

            modelBuilder.Entity("Denkiishi_v2.Models.LevelItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('nivel_iten_id_seq'::regclass)");

                    b.Property<int>("IdNivel")
                        .HasColumnType("integer")
                        .HasColumnName("id_nivel");

                    b.Property<int>("IdNivelItenObjeto")
                        .HasColumnType("integer")
                        .HasColumnName("id_nivel_iten_objeto");

                    b.Property<int>("IdObjeto")
                        .HasColumnType("integer")
                        .HasColumnName("id_objeto");

                    b.HasKey("Id")
                        .HasName("nivel_iten_id_pk");

                    b.HasIndex("IdNivel");

                    b.HasIndex("IdNivelItenObjeto");

                    b.ToTable("level_item", (string)null);
                });

            modelBuilder.Entity("Denkiishi_v2.Models.LevelItemType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('nivel_iten_objetoid_seq'::regclass)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.HasKey("Id")
                        .HasName("nivel_iten_objeto_id_pk");

                    b.ToTable("level_item_type", (string)null);
                });

            modelBuilder.Entity("Denkiishi_v2.Models.Radical", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short?>("KangxiNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("kangxi_number");

                    b.Property<string>("Literal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("literal");

                    b.Property<char?>("PathImg")
                        .HasColumnType("char")
                        .HasColumnName("path_img");

                    b.Property<short?>("StrokeCount")
                        .HasColumnType("smallint")
                        .HasColumnName("stroke_count");

                    b.Property<string>("UnicodeCode")
                        .HasColumnType("text")
                        .HasColumnName("unicode_code");

                    b.Property<int?>("WanikaniId")
                        .HasColumnType("integer")
                        .HasColumnName("wanikani_id");

                    b.HasKey("Id")
                        .HasName("radical_pkey");

                    b.HasIndex(new[] { "WanikaniId" }, "idx_radical_wanikani_id");

                    b.HasIndex(new[] { "UnicodeCode" }, "radical_unicode_code_key")
                        .IsUnique();

                    b.ToTable("radical", (string)null);
                });

            modelBuilder.Entity("Denkiishi_v2.Models.RadicalMeaning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descrition");

                    b.Property<int?>("IdLanguage")
                        .HasColumnType("integer")
                        .HasColumnName("id_language");

                    b.Property<int?>("IdRadical")
                        .HasColumnType("integer")
                        .HasColumnName("id_radical");

                    b.HasKey("Id")
                        .HasName("radical_reading_id_pk");

                    b.HasIndex("IdLanguage");

                    b.HasIndex("IdRadical");

                    b.ToTable("radical_meaning", (string)null);
                });

            modelBuilder.Entity("Denkiishi_v2.Models.ReviewHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('historico_revisao_id_historico_seq'::regclass)");

                    b.Property<int>("CardId")
                        .HasColumnType("integer")
                        .HasColumnName("card_id");

                    b.Property<int>("IntervalUsed")
                        .HasColumnType("integer")
                        .HasColumnName("interval_used");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<DateTime?>("ReviewedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("historico_revisao_pkey");

                    b.HasIndex("CardId");

                    b.HasIndex(new[] { "UserId", "ReviewedAt" }, "idx_usuario_historico");

                    b.ToTable("review_history", (string)null);
                });

            modelBuilder.Entity("Denkiishi_v2.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('usuarios_id_usuario_seq'::regclass)");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("RegisteredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("usuarios_pkey");

                    b.HasIndex(new[] { "Email" }, "usuarios_email_key")
                        .IsUnique();

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Denkiishi_v2.Models.UserNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('usuario_anotacao_id_seq'::regclass)");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("KanjiId")
                        .HasColumnType("integer")
                        .HasColumnName("kanji_id");

                    b.Property<int>("RadicalId")
                        .HasColumnType("integer")
                        .HasColumnName("radical_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("usuario_anotacao_pkey");

                    b.HasIndex("KanjiId");

                    b.HasIndex("RadicalId");

                    b.HasIndex("UserId");

                    b.ToTable("user_note", (string)null);
                });

            modelBuilder.Entity("Denkiishi_v2.Models.UserProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('progresso_usuario_id_progresso_seq'::regclass)");

                    b.Property<int>("CardId")
                        .HasColumnType("integer")
                        .HasColumnName("card_id");

                    b.Property<int>("ConsecutiveCorrectCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("consecutive_correct_count");

                    b.Property<decimal>("EaseFactor")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("ease_factor")
                        .HasDefaultValueSql("2.50");

                    b.Property<int>("Interval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("interval");

                    b.Property<DateTime?>("LastReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_reviewed_at");

                    b.Property<DateTime>("NextReviewAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_review_at");

                    b.Property<int>("ReviewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("review_count");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("progresso_usuario_pkey");

                    b.HasIndex("CardId");

                    b.HasIndex(new[] { "NextReviewAt" }, "idx_proxima_revisao");

                    b.HasIndex(new[] { "UserId", "CardId" }, "idx_usuario_cartao_progresso");

                    b.HasIndex(new[] { "UserId", "CardId" }, "progresso_usuario_id_usuario_id_cartao_key")
                        .IsUnique();

                    b.ToTable("user_progress", (string)null);
                });

            modelBuilder.Entity("Denkiishi_v2.Models.UserSynonym", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('usuario_sinonimo_kanji_radical_id_seq'::regclass)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("KanjiId")
                        .HasColumnType("integer")
                        .HasColumnName("kanji_id");

                    b.Property<int>("RadicalId")
                        .HasColumnType("integer")
                        .HasColumnName("radical_id");

                    b.Property<string>("SynonymText")
                        .HasColumnType("text")
                        .HasColumnName("synonym_text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("usuario_sinonimo_kanji_radical_pkey");

                    b.HasIndex("KanjiId");

                    b.HasIndex("RadicalId");

                    b.HasIndex("UserId");

                    b.ToTable("user_synonym", (string)null);
                });

            modelBuilder.Entity("Denkiishi_v2.Models.Vocabulary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Characters")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("characters");

                    b.Property<short?>("Level")
                        .HasColumnType("smallint")
                        .HasColumnName("level");

                    b.Property<string>("MeaningMnemonic")
                        .HasColumnType("text")
                        .HasColumnName("meaning_mnemonic");

                    b.Property<string>("ReadingMnemonic")
                        .HasColumnType("text")
                        .HasColumnName("reading_mnemonic");

                    b.Property<int?>("WanikaniId")
                        .HasColumnType("integer")
                        .HasColumnName("wanikani_id");

                    b.HasKey("Id")
                        .HasName("vocabulary_pkey");

                    b.HasIndex(new[] { "WanikaniId" }, "vocabulary_wanikani_id_key")
                        .IsUnique();

                    b.ToTable("vocabulary", (string)null);
                });

            modelBuilder.Entity("Denkiishi_v2.Models.VocabularyContextSentence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("En")
                        .HasColumnType("text")
                        .HasColumnName("en");

                    b.Property<string>("Ja")
                        .HasColumnType("text")
                        .HasColumnName("ja");

                    b.Property<int>("VocabularyId")
                        .HasColumnType("integer")
                        .HasColumnName("vocabulary_id");

                    b.HasKey("Id")
                        .HasName("vocabulary_context_sentence_pkey");

                    b.HasIndex("VocabularyId");

                    b.ToTable("vocabulary_context_sentence", (string)null);
                });

            modelBuilder.Entity("Denkiishi_v2.Models.VocabularyMeaning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("meaning");

                    b.Property<int>("VocabularyId")
                        .HasColumnType("integer")
                        .HasColumnName("vocabulary_id");

                    b.HasKey("Id")
                        .HasName("vocabulary_meaning_pkey");

                    b.HasIndex("VocabularyId");

                    b.ToTable("vocabulary_meaning", (string)null);
                });

            modelBuilder.Entity("Denkiishi_v2.Models.VocabularyReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<string>("Reading")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reading");

                    b.Property<int>("VocabularyId")
                        .HasColumnType("integer")
                        .HasColumnName("vocabulary_id");

                    b.HasKey("Id")
                        .HasName("vocabulary_reading_pkey");

                    b.HasIndex("VocabularyId");

                    b.ToTable("vocabulary_reading", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RadicalKanjiMap", b =>
                {
                    b.Property<int>("RadicalId")
                        .HasColumnType("integer")
                        .HasColumnName("radical_id");

                    b.Property<int>("KanjiId")
                        .HasColumnType("integer")
                        .HasColumnName("kanji_id");

                    b.HasKey("RadicalId", "KanjiId")
                        .HasName("radical_kanji_map_pkey");

                    b.HasIndex("KanjiId");

                    b.ToTable("radical_kanji_map", (string)null);
                });

            modelBuilder.Entity("VocabularyComposition", b =>
                {
                    b.Property<int>("VocabularyId")
                        .HasColumnType("integer")
                        .HasColumnName("vocabulary_id");

                    b.Property<int>("KanjiId")
                        .HasColumnType("integer")
                        .HasColumnName("kanji_id");

                    b.HasKey("VocabularyId", "KanjiId")
                        .HasName("vocabulary_composition_pkey");

                    b.HasIndex("KanjiId");

                    b.ToTable("vocabulary_composition", (string)null);
                });

            modelBuilder.Entity("Denkiishi_v2.Models.Card", b =>
                {
                    b.HasOne("Denkiishi_v2.Models.Deck", "Deck")
                        .WithMany("Cards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_baralho_cartao");

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("Denkiishi_v2.Models.Deck", b =>
                {
                    b.HasOne("Denkiishi_v2.Models.User", "User")
                        .WithMany("Decks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_baralho");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Denkiishi_v2.Models.KanjiDecomposition", b =>
                {
                    b.HasOne("Denkiishi_v2.Models.Kanji", "ComponentKanji")
                        .WithMany("KanjiDecompositionComponentKanjis")
                        .HasForeignKey("ComponentKanjiId")
                        .HasConstraintName("kanji_decomposition_component_kanji_id_fkey");

                    b.HasOne("Denkiishi_v2.Models.Radical", "ComponentRadical")
                        .WithMany("KanjiDecompositions")
                        .HasForeignKey("ComponentRadicalId")
                        .HasConstraintName("kanji_decomposition_component_radical_id_fkey");

                    b.HasOne("Denkiishi_v2.Models.Kanji", "ParentKanji")
                        .WithMany("KanjiDecompositionParentKanjis")
                        .HasForeignKey("ParentKanjiId")
                        .IsRequired()
                        .HasConstraintName("kanji_decomposition_parent_kanji_id_fkey");

                    b.Navigation("ComponentKanji");

                    b.Navigation("ComponentRadical");

                    b.Navigation("ParentKanji");
                });

            modelBuilder.Entity("Denkiishi_v2.Models.KanjiMeaning", b =>
                {
                    b.HasOne("Denkiishi_v2.Models.Language", "IdLanguageNavigation")
                        .WithMany("KanjiMeanings")
                        .HasForeignKey("IdLanguage")
                        .HasConstraintName("kanji_meaning_id_language_fk");

                    b.HasOne("Denkiishi_v2.Models.Kanji", "Kanji")
                        .WithMany("KanjiMeanings")
                        .HasForeignKey("KanjiId")
                        .IsRequired()
                        .HasConstraintName("kanji_meaning_kanji_id_fkey");

                    b.Navigation("IdLanguageNavigation");

                    b.Navigation("Kanji");
                });

            modelBuilder.Entity("Denkiishi_v2.Models.KanjiRadical", b =>
                {
                    b.HasOne("Denkiishi_v2.Models.Kanji", "Kanji")
                        .WithMany("KanjiRadicals")
                        .HasForeignKey("KanjiId")
                        .IsRequired()
                        .HasConstraintName("kanji_radical_kanji_id_fkey");

                    b.HasOne("Denkiishi_v2.Models.Radical", "Radical")
                        .WithMany("KanjiRadicals")
                        .HasForeignKey("RadicalId")
                        .IsRequired()
                        .HasConstraintName("kanji_radical_radical_id_fkey");

                    b.Navigation("Kanji");

                    b.Navigation("Radical");
                });

            modelBuilder.Entity("Denkiishi_v2.Models.KanjiReading", b =>
                {
                    b.HasOne("Denkiishi_v2.Models.Kanji", "Kanji")
                        .WithMany("KanjiReadings")
                        .HasForeignKey("KanjiId")
                        .IsRequired()
                        .HasConstraintName("kanji_reading_kanji_id_fkey");

                    b.Navigation("Kanji");
                });

            modelBuilder.Entity("Denkiishi_v2.Models.KanjiSimilarity", b =>
                {
                    b.HasOne("Denkiishi_v2.Models.Kanji", "IdKanjiNavigation")
                        .WithMany("KanjiSimilarityIdKanjiNavigations")
                        .HasForeignKey("IdKanji")
                        .HasConstraintName("kanji_similaridade_id_kanji");

                    b.HasOne("Denkiishi_v2.Models.Kanji", "IdKanjiSimilarNavigation")
                        .WithMany("KanjiSimilarityIdKanjiSimilarNavigations")
                        .HasForeignKey("IdKanjiSimilar")
                        .HasConstraintName("kanji_similaridade_id_kanji_similar");

                    b.Navigation("IdKanjiNavigation");

                    b.Navigation("IdKanjiSimilarNavigation");
                });

            modelBuilder.Entity("Denkiishi_v2.Models.Lesson", b =>
                {
                    b.HasOne("Denkiishi_v2.Models.Kanji", "IdKanjiNavigation")
                        .WithMany("Lessons")
                        .HasForeignKey("IdKanji")
                        .HasConstraintName("lesson_id_kanji_fk");

                    b.HasOne("Denkiishi_v2.Models.Radical", "IdRadicalNavigation")
                        .WithMany("Lessons")
                        .HasForeignKey("IdRadical")
                        .HasConstraintName("lesson_id_radical_fk");

                    b.HasOne("Denkiishi_v2.Models.Vocabulary", "Vocabulary")
                        .WithMany("Lessons")
                        .HasForeignKey("VocabularyId")
                        .HasConstraintName("lesson_id_vocabulario_fk");

                    b.Navigation("IdKanjiNavigation");

                    b.Navigation("IdRadicalNavigation");

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("Denkiishi_v2.Models.LevelItem", b =>
                {
                    b.HasOne("Denkiishi_v2.Models.Level", "IdNivelNavigation")
                        .WithMany("LevelItems")
                        .HasForeignKey("IdNivel")
                        .IsRequired()
                        .HasConstraintName("nivel_iten_id_nivel_fk");

                    b.HasOne("Denkiishi_v2.Models.LevelItemType", "IdNivelItenObjetoNavigation")
                        .WithMany("LevelItems")
                        .HasForeignKey("IdNivelItenObjeto")
                        .IsRequired()
                        .HasConstraintName("nivel_iten_id_nivel_iten_objeto_fk");

                    b.Navigation("IdNivelItenObjetoNavigation");

                    b.Navigation("IdNivelNavigation");
                });

            modelBuilder.Entity("Denkiishi_v2.Models.RadicalMeaning", b =>
                {
                    b.HasOne("Denkiishi_v2.Models.Language", "IdLanguageNavigation")
                        .WithMany("RadicalMeanings")
                        .HasForeignKey("IdLanguage")
                        .HasConstraintName("radical_reading_id_language_fk");

                    b.HasOne("Denkiishi_v2.Models.Radical", "IdRadicalNavigation")
                        .WithMany("RadicalMeanings")
                        .HasForeignKey("IdRadical")
                        .HasConstraintName("radical_reading_id_radical_fk");

                    b.Navigation("IdLanguageNavigation");

                    b.Navigation("IdRadicalNavigation");
                });

            modelBuilder.Entity("Denkiishi_v2.Models.ReviewHistory", b =>
                {
                    b.HasOne("Denkiishi_v2.Models.Card", "Card")
                        .WithMany("ReviewHistories")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cartao_historico");

                    b.HasOne("Denkiishi_v2.Models.User", "User")
                        .WithMany("ReviewHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_historico");

                    b.Navigation("Card");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Denkiishi_v2.Models.UserNote", b =>
                {
                    b.HasOne("Denkiishi_v2.Models.Kanji", "Kanji")
                        .WithMany("UserNotes")
                        .HasForeignKey("KanjiId")
                        .IsRequired()
                        .HasConstraintName("usuario_anotacao_id_kanji_fkey");

                    b.HasOne("Denkiishi_v2.Models.Radical", "Radical")
                        .WithMany("UserNotes")
                        .HasForeignKey("RadicalId")
                        .IsRequired()
                        .HasConstraintName("usuario_anotacao_id_radical_fkey");

                    b.HasOne("Denkiishi_v2.Models.User", "User")
                        .WithMany("UserNotes")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("usuario_anotacao_id_usuario_fkey");

                    b.Navigation("Kanji");

                    b.Navigation("Radical");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Denkiishi_v2.Models.UserProgress", b =>
                {
                    b.HasOne("Denkiishi_v2.Models.Card", "Card")
                        .WithMany("UserProgresses")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cartao_progresso");

                    b.HasOne("Denkiishi_v2.Models.User", "User")
                        .WithMany("UserProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_progresso");

                    b.Navigation("Card");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Denkiishi_v2.Models.UserSynonym", b =>
                {
                    b.HasOne("Denkiishi_v2.Models.Kanji", "Kanji")
                        .WithMany("UserSynonyms")
                        .HasForeignKey("KanjiId")
                        .IsRequired()
                        .HasConstraintName("usuario_sinonimo_kanji_radical_id_kanji_fkey");

                    b.HasOne("Denkiishi_v2.Models.Radical", "Radical")
                        .WithMany("UserSynonyms")
                        .HasForeignKey("RadicalId")
                        .IsRequired()
                        .HasConstraintName("usuario_sinonimo_kanji_radical_id_radical_fkey");

                    b.HasOne("Denkiishi_v2.Models.User", "User")
                        .WithMany("UserSynonyms")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("usuario_sinonimo_kanji_radical_id_usuario_fkey");

                    b.Navigation("Kanji");

                    b.Navigation("Radical");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Denkiishi_v2.Models.VocabularyContextSentence", b =>
                {
                    b.HasOne("Denkiishi_v2.Models.Vocabulary", "Vocabulary")
                        .WithMany("VocabularyContextSentences")
                        .HasForeignKey("VocabularyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("vocabulary_context_sentence_vocabulary_id_fkey");

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("Denkiishi_v2.Models.VocabularyMeaning", b =>
                {
                    b.HasOne("Denkiishi_v2.Models.Vocabulary", "Vocabulary")
                        .WithMany("VocabularyMeanings")
                        .HasForeignKey("VocabularyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("vocabulary_meaning_vocabulary_id_fkey");

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("Denkiishi_v2.Models.VocabularyReading", b =>
                {
                    b.HasOne("Denkiishi_v2.Models.Vocabulary", "Vocabulary")
                        .WithMany("VocabularyReadings")
                        .HasForeignKey("VocabularyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("vocabulary_reading_vocabulary_id_fkey");

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Denkiishi_v2.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Denkiishi_v2.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Denkiishi_v2.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Denkiishi_v2.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RadicalKanjiMap", b =>
                {
                    b.HasOne("Denkiishi_v2.Models.Kanji", null)
                        .WithMany()
                        .HasForeignKey("KanjiId")
                        .IsRequired()
                        .HasConstraintName("radical_kanji_map_kanji_id_fkey");

                    b.HasOne("Denkiishi_v2.Models.Radical", null)
                        .WithMany()
                        .HasForeignKey("RadicalId")
                        .IsRequired()
                        .HasConstraintName("radical_kanji_map_radical_id_fkey");
                });

            modelBuilder.Entity("VocabularyComposition", b =>
                {
                    b.HasOne("Denkiishi_v2.Models.Kanji", null)
                        .WithMany()
                        .HasForeignKey("KanjiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("vocabulary_composition_kanji_id_fkey");

                    b.HasOne("Denkiishi_v2.Models.Vocabulary", null)
                        .WithMany()
                        .HasForeignKey("VocabularyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("vocabulary_composition_vocabulary_id_fkey");
                });

            modelBuilder.Entity("Denkiishi_v2.Models.Card", b =>
                {
                    b.Navigation("ReviewHistories");

                    b.Navigation("UserProgresses");
                });

            modelBuilder.Entity("Denkiishi_v2.Models.Deck", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("Denkiishi_v2.Models.Kanji", b =>
                {
                    b.Navigation("KanjiDecompositionComponentKanjis");

                    b.Navigation("KanjiDecompositionParentKanjis");

                    b.Navigation("KanjiMeanings");

                    b.Navigation("KanjiRadicals");

                    b.Navigation("KanjiReadings");

                    b.Navigation("KanjiSimilarityIdKanjiNavigations");

                    b.Navigation("KanjiSimilarityIdKanjiSimilarNavigations");

                    b.Navigation("Lessons");

                    b.Navigation("UserNotes");

                    b.Navigation("UserSynonyms");
                });

            modelBuilder.Entity("Denkiishi_v2.Models.Language", b =>
                {
                    b.Navigation("KanjiMeanings");

                    b.Navigation("RadicalMeanings");
                });

            modelBuilder.Entity("Denkiishi_v2.Models.Level", b =>
                {
                    b.Navigation("LevelItems");
                });

            modelBuilder.Entity("Denkiishi_v2.Models.LevelItemType", b =>
                {
                    b.Navigation("LevelItems");
                });

            modelBuilder.Entity("Denkiishi_v2.Models.Radical", b =>
                {
                    b.Navigation("KanjiDecompositions");

                    b.Navigation("KanjiRadicals");

                    b.Navigation("Lessons");

                    b.Navigation("RadicalMeanings");

                    b.Navigation("UserNotes");

                    b.Navigation("UserSynonyms");
                });

            modelBuilder.Entity("Denkiishi_v2.Models.User", b =>
                {
                    b.Navigation("Decks");

                    b.Navigation("ReviewHistories");

                    b.Navigation("UserNotes");

                    b.Navigation("UserProgresses");

                    b.Navigation("UserSynonyms");
                });

            modelBuilder.Entity("Denkiishi_v2.Models.Vocabulary", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("VocabularyContextSentences");

                    b.Navigation("VocabularyMeanings");

                    b.Navigation("VocabularyReadings");
                });
#pragma warning restore 612, 618
        }
    }
}
